# taka's private drone server
# for v0.5

pipeline:
    build:
        #privileged: true
        image: takawang/dind:compose
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose rm -f
            - docker-compose build
            - docker-compose up --build --abort-on-container-exit
