# taka's private drone server

pipeline:
    build:
        privileged: true
        image: docker:dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker ps -a
            - docker-compose up --build