# taka's private drone server

pipeline:
    build:
        image: takawang/ubuntu-drone-psmb
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose up --build