# taka's private drone server
# for v0.5

pipeline:
    build:
        #privileged: true
        image: takawang/dind:compose
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - apk add --no-cache git
            - git clone https://github.com/taka-wang/dummy-psmb.git
            - git clone https://github.com/taka-wang/c-modbus-slave.git
            - docker-compose -f docker-compose.build rm -f -a
            - docker-compose -f docker-compose.build build
            - docker-compose -f docker-compose.build up --abort-on-container-exit
