# drone.io v0.4
# armhf


build:
    image: takawang/dind:$$arch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    commands:
        # build dummy-psmbtcp
        - docker build --no-cache=true -t edgepro/dummy-psmbtcp:$$arch -f test/dummy-psmbtcp/Dockerfile.$$arch test/dummy-psmbtcp/.
        # build modbusd
        - docker build --no-cache=true -t edgepro/modbusd:$$arch -f dockerfile/Dockerfile.$$arch .
        - docker push edgepro/modbusd:$$arch
        # CI
        - docker-compose -f dockerfile/docker-compose.$$arch rm -f -a
        - docker-compose -f dockerfile/docker-compose.$$arch build --no-cache
        - docker-compose -f dockerfile/docker-compose.$$arch up --abort-on-container-exit


matrix:
    arch:
        - armhf

