# drone.io v0.4
# armhf


build:
    image: takawang/dind:$$arch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    commands:
        # build dummy-psmbtcp
        - docker build --no-cache=true -t takawang/dummy-psmbtcp:armhf -f test/dummy-psmbtcp/Dockerfile.armhf test/dummy-psmbtcp/.
        # build modbusd
        - docker build --no-cache=true -t takawang/modbusd:armhf -f Dockerfile.armhf .
        # CI
        - docker-compose -f docker-compose.drone-armhf rm -f -a
        - docker-compose -f docker-compose.drone-armhf build
        - docker-compose -f docker-compose.drone-armhf up --abort-on-container-exit
        - docker-compose -f docker-compose.drone-armhf rm -f -a
        # deployment
        - docker push takawang/modbusd:armhf
        - docker push takawang/dummy-psmbtcp:armhf

matrix:
    arch:
        - armhf
