# taka's private drone server
# for v0.5

workspace:
    path: /drone # overwrite default path

pipeline:
    build:
        image: docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - git clone https://github.com/taka-wang/dummy-psmb.git
            - git clone https://github.com/taka-wang/c-modbus-slave.git
            - docker-compose -f docker-compose.drone rm -f -a
            - docker-compose -f docker-compose.drone build
            - docker-compose -f docker-compose.drone up --abort-on-container-exit
