# taka's private drone server
# for v0.5

workspace:
    path: /drone # overwrite default path

pipeline:
    build:
        image: takawang/dind:push
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # docker in docker trick
        commands:
            - docker build --build-arg MB=`(cat /etc/mb)` -t takawang/modbusd:alpine -f Dockerfile.alpine .
            - docker push takawang/modbusd:alpine

    ci:
        image: takawang/dind:push # docker in docker wiht compose
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # docker in docker trick
        commands:
            - docker-compose -f docker-compose.drone rm -f -a
            - docker-compose -f docker-compose.drone build
            - docker-compose -f docker-compose.drone up --abort-on-container-exit